### ISSUE TITLE
Question: Wrong use of handle_socket_error?

### ISSUE THREAD

**Issue by Menkir** [funbox/smppex#80]
Hi guys,
I have a session implementation that implements the handle_socket_error callback. Maybe it's because of my understanding, but when reading the API I assume that the callback is called exactly when a network error or similar occurs. I artificially triggered the error by cutting the internet connection. However, the callback was not called. The session runs into a timeout and is terminated. Am I getting something wrong?

**Comment by savonarola** [comment]
Hello!
I do not think loss of connection causes error state in a socket. And it doubtedly should — connection loss is an affair of lower OSI layers than ip and tcp. Lost connection can recover and TCP flow can continue.

That's why connection losses are effectevely detected by «pings» and SMPP is quite good in this with its `enquire_link` packets and SMPP timers.
